import os
import torch
import torch.nn as nn
import torch.nn.functional as F
from PIL import Image
import numpy as np
from tqdm import tqdm
import matplotlib.pyplot as plt
import matplotlib.cm as cm
from skimage import color, filters
from skimage.measure import label, regionprops
from scipy import ndimage
import pandas as pd
import re
import json # For loading preprocessing config

# --- CONFIGURATION ---
INFERENCE_INPUT_ROOT = "INFERENCE_INPUT" # Directory containing images directly
KEY_CSV_PATH = "key.csv" # Path to the key.csv file in the PWD
BEST_MODEL_PATH = "V2_VINI_best_model_vein_dice_0.6862_epoch19.pt" # Update with your best model path
OUTPUT_PREDICTIONS_DIR = "INFERENCE_OUTPUTS" # Output folder

# Path to the preprocessing config JSON (generated by your preprocessing script for this model)
PREPROCESSING_CONFIG_PATH = "PROCESSED_DATA_FOR_SEGMENTATION_VINIFERA/config/preprocessing_config.json"

# Subdirectories for organized output
OUTPUT_COMPONENT_MASKS_DIR = os.path.join(OUTPUT_PREDICTIONS_DIR, "COMPONENT_MASKS")
OUTPUT_COMPONENT_RGB_CROPS_DIR = os.path.join(OUTPUT_PREDICTIONS_DIR, "COMPONENT_RGB_CROPS")
OUTPUT_COMPONENT_OVERLAYS_DIR = os.path.join(OUTPUT_PREDICTIONS_DIR, "COMPONENT_OVERLAYS")
METADATA_CSV_PATH = os.path.join(OUTPUT_PREDICTIONS_DIR, "component_metadata.csv")

# Ensure output parent directory exists
os.makedirs(OUTPUT_PREDICTIONS_DIR, exist_ok=True)
# Ensure subdirectories exist
os.makedirs(OUTPUT_COMPONENT_MASKS_DIR, exist_ok=True)
os.makedirs(OUTPUT_COMPONENT_RGB_CROPS_DIR, exist_ok=True)
os.makedirs(OUTPUT_COMPONENT_OVERLAYS_DIR, exist_ok=True)

# Device configuration (harmonized with predict_leaf_segmentations.py)
DEVICE = torch.device("mps" if torch.backends.mps.is_available() else "cuda" if torch.cuda.is_available() else "cpu")
print(f"Using device: {DEVICE}")

# Model parameters
NUM_SEG_CLASSES = 3 # Background, Blade, Vein
IN_CHANNELS = 11 # As used in your UNet
NUM_GEO_CHANNELS = 1 # From the predict_leaf_segmentations.py UNet definition

# Filter parameter for connected components
MIN_BBOX_DIMENSION = 50 # Ignore components if any bounding box dimension is less than 50 pixels

# Overlay parameters (retained from WOLFSKILL script, not predict_leaf_segmentations.py's ImageDraw method)
VEIN_OVERLAY_COLORMAP_NAME = 'plasma'
VEIN_ALPHA = 1.0 # Alpha for vein overlay. Keep 1.0 for full opacity

# Dataset-specific prefix for connected component names
DATASET_PREFIX = "WOLFSKILL_" # New prefix for this dataset

# === LOAD PREPROCESSING CONFIGURATION ===
# This needs to match the config used during training your VINI model
try:
    if not os.path.exists(PREPROCESSING_CONFIG_PATH):
        raise FileNotFoundError(f"Preprocessing configuration file not found at: {PREPROCESSING_CONFIG_PATH}\n"
                                "Please ensure your preprocessing script has been run and saved the config.")
    with open(PREPROCESSING_CONFIG_PATH, 'r') as f:
        PREPROCESSING_CONFIG = json.load(f)

    TARGET_WIDTH = PREPROCESSING_CONFIG["TARGET_SIZE"][0]
    TARGET_HEIGHT = PREPROCESSING_CONFIG["TARGET_SIZE"][1]
    TARGET_SIZE = (TARGET_WIDTH, TARGET_HEIGHT)
    SATO_SIGMAS = PREPROCESSING_CONFIG["sato_sigmas"]
    MEIJERING_SIGMAS = PREPROCESSING_CONFIG["meijering_sigmas"]
    FRANGI_SIGMAS = PREPROCESSING_CONFIG["frangi_sigmas"]
    HESSIAN_SIGMAS = PREPROCESSING_CONFIG["hessian_sigmas"]
    ENHANCE_PERCENTILE = PREPROCESSING_CONFIG["ENHANCE_PERCENTILE"]
    print(f"Preprocessing configuration loaded from {PREPROCESSING_CONFIG_PATH}")
    print(f"Target size: {TARGET_SIZE}, Enhance Percentile: {ENHANCE_PERCENTILE}")
except Exception as e:
    print(f"Error loading preprocessing config: {e}")
    print("Please ensure PREPROCESSING_CONFIG_PATH is correct and the JSON file is valid.")
    exit() # Exit if config cannot be loaded, as it's critical for preprocessing

# === HELPER FUNCTIONS (COPIED AND MODIFIED FROM predict_leaf_segmentations.py) ===
def rotate_to_wide(image_pil):
    """Rotates an image so its width is greater than its height."""
    width, height = image_pil.size
    rotation_applied = False
    if height > width:
        image_pil = image_pil.transpose(Image.Transpose.ROTATE_270)
        rotation_applied = True
    return image_pil, rotation_applied

def rescale_and_pad_image(image_pil, target_size):
    """
    Rescales an image to fit within target_size while maintaining aspect ratio,
    then pads with white (for RGB) or black (for L) to reach target_size.
    Also returns the paste offset, scaled dimensions, and scale factor.
    """
    original_width, original_height = image_pil.size
    target_width, target_height = target_size
    
    scale_w = target_width / original_width
    scale_h = target_height / original_height
    scale_factor = min(scale_w, scale_h)

    if original_width == 0 or original_height == 0:
        # Return a white padded image for RGB if dimensions are invalid
        return Image.new("RGB", target_size, (255, 255, 255)), (0, 0), (0, 0), 0.0

    new_width = int(original_width * scale_factor)
    new_height = int(original_height * scale_factor)

    scaled_img = image_pil.resize((new_width, new_height), Image.LANCZOS)

    paste_x = (target_width - new_width) // 2
    paste_y = (target_height - new_height) // 2

    # Use white for RGB background as per the original preprocessing
    padded_img = Image.new("RGB", target_size, (255, 255, 255))
    padded_img.paste(scaled_img, (paste_x, paste_y))
    
    return padded_img, (paste_x, paste_y), (new_width, new_height), scale_factor

# Re-defined as per predict_leaf_segmentations.py to use percentile_val argument
def enhance_contrast(arr, percentile_val):
    """Applies contrast enhancement based on percentile."""
    if arr.size == 0:
        return np.array([])
    vmax = np.percentile(arr, percentile_val)
    if vmax == 0:
        return np.zeros_like(arr, dtype=np.float32)
    arr_clipped = np.clip(arr, 0, vmax)
    arr_rescaled = arr_clipped / vmax
    return arr_rescaled.astype(np.float32)

def apply_ridge_filters(image_pil_padded, sato_s, meijering_s, frangi_s, hessian_s, enhance_p):
    """
    Applies various ridge filters to a grayscale image and returns their enhanced outputs.
    Generates both black_ridges=True and False versions for Sato, Meijering, Frangi.
    Generates both black_ridges=True and False versions for Hessian.
    Takes a PIL Image that is already padded to TARGET_SIZE.
    """
    image_rgb_float = np.array(image_pil_padded).astype(np.float32) / 255.0
    
    if image_rgb_float.ndim == 3 and image_rgb_float.shape[2] == 3:
        gray_image = color.rgb2gray(image_rgb_float)
    elif image_rgb_float.ndim == 2:
        gray_image = image_rgb_float
    else:
        raise ValueError(f"Unexpected image dimensions or mode for filter application: {image_rgb_float.shape}")

    # --- Sato Filter ---
    sato_br_false_raw = filters.sato(gray_image, sigmas=sato_s, black_ridges=False, mode='reflect')
    sato_br_true_raw = filters.sato(gray_image, sigmas=sato_s, black_ridges=True, mode='reflect')
    sato_br_false_processed = enhance_contrast(sato_br_false_raw, enhance_p)
    sato_br_true_processed = enhance_contrast(sato_br_true_raw, enhance_p)

    # --- Meijering Filter ---
    meijering_br_false_raw = filters.meijering(gray_image, sigmas=meijering_s, black_ridges=False, mode='reflect')
    meijering_br_true_raw = filters.meijering(gray_image, sigmas=meijering_s, black_ridges=True, mode='reflect')
    meijering_br_false_processed = enhance_contrast(meijering_br_false_raw, enhance_p)
    meijering_br_true_processed = enhance_contrast(meijering_br_true_raw, enhance_p)

    # --- Frangi Filter ---
    frangi_br_false_raw = filters.frangi(gray_image, sigmas=frangi_s, black_ridges=False, mode='reflect')
    frangi_br_true_raw = filters.frangi(gray_image, sigmas=frangi_s, black_ridges=True, mode='reflect')
    frangi_br_false_processed = enhance_contrast(frangi_br_false_raw, enhance_p)
    frangi_br_true_processed = enhance_contrast(frangi_br_true_raw, enhance_p)

    # --- Hessian Filter ---
    hessian_br_true_raw = filters.hessian(gray_image, sigmas=hessian_s, black_ridges=True, mode='reflect')
    hessian_br_false_raw = filters.hessian(gray_image, sigmas=hessian_s, black_ridges=False, mode='reflect')
    hessian_br_true_processed = enhance_contrast(hessian_br_true_raw, enhance_p)
    hessian_br_false_processed = enhance_contrast(hessian_br_false_raw, enhance_p)

    return (sato_br_false_processed, sato_br_true_processed,
            meijering_br_false_processed, meijering_br_true_processed,
            frangi_br_false_processed, frangi_br_true_processed,
            hessian_br_true_processed, hessian_br_false_processed) # 8 channels

def create_11channel_input(img_pil_padded, sato_s, meijering_s, frangi_s, hessian_s, enhance_p):
    """
    Creates the 11-channel input array for the UNet model, matching the preprocessing script.
    Channels: L, A, B, Sato_F, Sato_T, Meijering_F, Meijering_T, Frangi_F, Frangi_T, Hessian_T, Hessian_F.
    """
    img_rgb_float = np.array(img_pil_padded).astype(np.float32) / 255.0
    img_lab = color.rgb2lab(img_rgb_float)

    L_channel = img_lab[:, :, 0] / 100.0  # L channel normalized to 0-1
    A_channel = (img_lab[:, :, 1] + 128) / 255.0  # A channel normalized to 0-1
    B_channel = (img_lab[:, :, 2] + 128) / 255.0  # B channel normalized to 0-1

    sato_f, sato_t, meijering_f, meijering_t, frangi_f, frangi_t, hessian_t, hessian_f = \
        apply_ridge_filters(img_pil_padded, sato_s, meijering_s, frangi_s, hessian_s, enhance_p)

    eleven_channels = np.stack([L_channel, A_channel, B_channel,
                                sato_f, sato_t, meijering_f, meijering_t,
                                frangi_f, frangi_t, hessian_t, hessian_f], axis=-1)
    
    return eleven_channels


# ===================== U-Net Model Definition (harmonized with predict_leaf_segmentations.py) =====================
class UNet(nn.Module):
    def __init__(self, in_channels, num_seg_classes, num_geo_channels):
        super().__init__()

        def CBR(in_ch, out_ch):
            return nn.Sequential(
                nn.Conv2d(in_ch, out_ch, 3, padding=1),
                nn.BatchNorm2d(out_ch),
                nn.ReLU(inplace=True)
            )

        # Encoder path
        self.enc1 = nn.Sequential(CBR(in_channels, 64), CBR(64, 64))
        self.enc2 = nn.Sequential(CBR(64, 128), CBR(128, 128))
        self.enc3 = nn.Sequential(CBR(128, 256), CBR(256, 256))
        self.enc4 = nn.Sequential(CBR(256, 512), CBR(512, 512))

        self.pool = nn.MaxPool2d(2)

        # Decoder path
        self.up4 = nn.ConvTranspose2d(512, 256, 2, stride=2)
        self.dec4 = nn.Sequential(CBR(512, 256), CBR(256, 256))

        self.up3 = nn.ConvTranspose2d(256, 128, 2, stride=2)
        self.dec3 = nn.Sequential(CBR(256, 128), CBR(128, 128))

        self.up2 = nn.ConvTranspose2d(128, 64, 2, stride=2)
        self.dec2 = nn.Sequential(CBR(128, 64), CBR(64, 64))

        # Separate output heads
        self.seg_out_conv = nn.Conv2d(64, num_seg_classes, 1) # Output for segmentation (3 classes)
        self.geo_out_conv = nn.Sequential(
            nn.Conv2d(64, num_geo_channels, 1),
            nn.Sigmoid() # Common for normalized regression outputs
        )

    def forward(self, x):
        # Encoder
        e1 = self.enc1(x)
        e2 = self.enc2(self.pool(e1))
        e3 = self.enc3(self.pool(e2))
        e4 = self.enc4(self.pool(e3))

        # Decoder
        d4 = self.up4(e4)
        if d4.shape != e3.shape:
            d4 = F.interpolate(d4, size=e3.shape[2:], mode='bilinear', align_corners=False)
        d4 = torch.cat([d4, e3], dim=1)
        d4 = self.dec4(d4)

        d3 = self.up3(d4)
        if d3.shape != e2.shape:
            d3 = F.interpolate(d3, size=e2.shape[2:], mode='bilinear', align_corners=False)
        d3 = torch.cat([d3, e2], dim=1)
        d3 = self.dec3(d3)

        d2 = self.up2(d3)
        if d2.shape != e1.shape:
            d2 = F.interpolate(d2, size=e1.shape[2:], mode='bilinear', align_corners=False)
        d2 = torch.cat([d2, e1], dim=1)
        d2 = self.dec2(d2)

        # Pass through separate output heads
        seg_output = self.seg_out_conv(d2)
        geo_output = self.geo_out_conv(d2)
        
        return seg_output, geo_output

# --- String Sanitization Function (retained from previous WOLFSKILL script) ---
def sanitize_filename_string(s):
    """
    Sanitizes a string to be suitable for use in a filename.
    Replaces problematic characters with underscores.
    """
    s = s.strip()
    # Replace any character that is not a letter, number, hyphen, underscore, or dot with an underscore
    s = re.sub(r'[^\w\s\-\.]', '_', s)
    # Replace spaces with underscores
    s = s.replace(' ', '_')
    # Remove multiple consecutive underscores
    s = re.sub(r'_{2,}', '_', s)
    # Remove leading/trailing underscores
    s = s.strip('_')
    return s

# --- Main Prediction Loop ---
def main():
    # Load the trained model
    # Pass correct output channel arguments to UNet constructor
    model = UNet(in_channels=IN_CHANNELS, num_seg_classes=NUM_SEG_CLASSES, num_geo_channels=NUM_GEO_CHANNELS).to(DEVICE)
    if os.path.exists(BEST_MODEL_PATH):
        print(f"Loading model from {BEST_MODEL_PATH}...")
        model.load_state_dict(torch.load(BEST_MODEL_PATH, map_location=DEVICE))
        model.eval() # Set model to evaluation mode
        print("Model loaded successfully.")
    else:
        print(f"Error: Model checkpoint not found at {BEST_MODEL_PATH}")
        return

    # --- Load key.csv for cultivar lookup ---
    cultivar_lookup = {}
    if os.path.exists(KEY_CSV_PATH):
        print(f"Loading key.csv from {KEY_CSV_PATH}...")
        key_df = pd.read_csv(KEY_CSV_PATH)
        for _, row in key_df.iterrows():
            try:
                block = str(row['block']).strip().upper()
                # Ensure row and vine are zero-padded to two digits
                row_str = f"{int(row['row']):02d}"
                vine_str = f"{int(row['vine']):02d}"
                
                # Construct the filename prefix (e.g., K0408)
                file_prefix = f"{block}{row_str}{vine_str}"
                cultivar = str(row['cultivar']).strip()
                cultivar_lookup[file_prefix] = cultivar
            except Exception as e:
                print(f"Warning: Could not parse row in key.csv: {row.to_dict()}. Error: {e}")
        print(f"Loaded {len(cultivar_lookup)} cultivar entries from key.csv.")
    else:
        print(f"Error: key.csv not found at {KEY_CSV_PATH}. Cannot map filenames to cultivars.")
        return

    # --- Resumable Prediction Logic ---
    processed_original_images = set()
    all_component_metadata = []
    
    # Initialize global_component_serial_id
    global_component_serial_id = 1 

    if os.path.exists(METADATA_CSV_PATH):
        print(f"Metadata CSV found at {METADATA_CSV_PATH}. Loading existing data for resuming...")
        existing_df = pd.read_csv(METADATA_CSV_PATH)
        all_component_metadata = existing_df.to_dict('records')
        processed_original_images = set(existing_df['original_image_path'].unique())
        
        # Determine the next available global_component_serial_id
        if not existing_df.empty:
            max_existing_id = 0
            for comp_name in existing_df['component_name']:
                try:
                    # Split at the last underscore to get the number
                    parts = comp_name.rsplit('_', 1)
                    # Check if the name starts with the current DATASET_PREFIX to avoid mixing IDs from ALGERIA and WOLFSKILL
                    if len(parts) > 1 and parts[0].startswith(DATASET_PREFIX):
                        max_existing_id = max(max_existing_id, int(parts[-1]))
                except ValueError:
                    pass
            global_component_serial_id = max_existing_id + 1

        print(f"Found {len(processed_original_images)} unique original images already processed. Resuming...")
        print(f"Next global component ID will start from: {global_component_serial_id}")
    else:
        # Create empty CSV with header if it doesn't exist
        print(f"Metadata CSV not found. Creating a new one at {METADATA_CSV_PATH}")
        metadata_df = pd.DataFrame(columns=[
            "original_image_path", "cultivar", 
            "component_name", 
            "component_idx_in_original_image", 
            "blade_pixels", "vein_pixels", "background_pixels_internal_holes", 
            "total_bbox_pixels", "bbox_min_row", "bbox_min_col", "bbox_max_row", "bbox_max_col",
            "mask_file", "rgb_crop_file", "overlay_file"
        ])
        metadata_df.to_csv(METADATA_CSV_PATH, index=False)


    # Get the colormap for vein overlay
    vein_cmap = plt.colormaps.get_cmap(VEIN_OVERLAY_COLORMAP_NAME)

    # Collect all image paths to process directly from INFERENCE_INPUT
    images_to_process = []
    for fname in sorted(os.listdir(INFERENCE_INPUT_ROOT)):
        # Using a more robust check for image extensions
        if any(fname.lower().endswith(ext) for ext in [".jpg", ".jpeg", ".png", ".tif", ".tiff"]):
            full_image_path = os.path.join(INFERENCE_INPUT_ROOT, fname)
            images_to_process.append((fname, full_image_path))
    
    # Filter out already processed images
    filtered_images_to_process = []
    for fname, full_image_path in images_to_process:
        if full_image_path not in processed_original_images:
            filtered_images_to_process.append((fname, full_image_path))
    
    # Use tqdm on the filtered list for accurate progress
    print(f"Starting processing on {len(filtered_images_to_process)} new images.")
    for fname, original_image_full_path in tqdm(filtered_images_to_process, desc="Overall Prediction Progress"):
        
        # This image will be processed, so add its path to the set for the current run
        processed_original_images.add(original_image_full_path)

        # --- Determine Cultivar for the current image ---
        file_base_name_no_ext = os.path.splitext(fname)[0]
        match = re.match(r'^[A-Za-z]\d{4}', file_base_name_no_ext)
        image_file_prefix_for_lookup = None
        if match:
            image_file_prefix_for_lookup = match.group(0).upper() 
        
        current_cultivar = "UNKNOWN_CULTIVAR" 
        if image_file_prefix_for_lookup and image_file_prefix_for_lookup in cultivar_lookup:
            current_cultivar = cultivar_lookup[image_file_prefix_for_lookup]
        else:
            print(f"Warning: Cultivar for {fname} (prefix '{image_file_prefix_for_lookup}') not found in key.csv. Using '{current_cultivar}'.")
        
        # Sanitize cultivar name for use in filenames
        sanitized_cultivar = sanitize_filename_string(current_cultivar)

        try:
            # Load original image
            original_pil_img = Image.open(original_image_full_path).convert("RGB")

            # Preprocess for 11-channels (matching training pipeline)
            img_pil_preprocessed_rot, _ = rotate_to_wide(original_pil_img.copy())
            img_pil_padded_for_model, paste_offset, scaled_dims, scale_factor_applied = \
                rescale_and_pad_image(img_pil_preprocessed_rot, TARGET_SIZE)

            # Generate the 11-channel input from this padded image for the model
            eleven_channel_data_np = create_11channel_input(
                img_pil_padded_for_model, SATO_SIGMAS, MEIJERING_SIGMAS, FRANGI_SIGMAS, HESSIAN_SIGMAS, ENHANCE_PERCENTILE
            )
            
            # Convert numpy array to PyTorch tensor, add batch dimension, move to device
            image_tensor = torch.from_numpy(eleven_channel_data_np).permute(2, 0, 1).float().unsqueeze(0).to(DEVICE)

            # Perform prediction
            with torch.no_grad():
                seg_output_logits, _ = model(image_tensor) # Discard geo_output
            
            # Process Segmentation Output: Apply softmax and argmax
            predicted_seg_mask_padded = torch.argmax(F.softmax(seg_output_logits, dim=1).squeeze(0), dim=0).cpu().numpy() # (H, W)

            # --- Reverse padding and rotation if necessary ---
            # Create a full-size blank mask corresponding to the *rotated, unpadded* image
            # This is complex: need to unpad and unrotate the mask to match original_rgb_np before cropping
            unpadded_mask = np.zeros((scaled_dims[1], scaled_dims[0]), dtype=predicted_seg_mask_padded.dtype)
            unpadded_mask = predicted_seg_mask_padded[
                paste_offset[1] : paste_offset[1] + scaled_dims[1],
                paste_offset[0] : paste_offset[0] + scaled_dims[0]
            ]
            
            # Resize the unpadded mask back to original pre-rotated size
            # Use nearest-neighbor for mask resizing to preserve integer labels
            original_unrotated_width, original_unrotated_height = original_pil_img.size
            
            # If the image was rotated to wide, we need to rotate the mask back
            if original_unrotated_height > original_unrotated_width: # Image was rotated 270 deg (clockwise)
                 # Rotate the mask 90 degrees counter-clockwise to undo the 270 clockwise rotation
                 unpadded_mask = np.rot90(unpadded_mask, k=1) # k=1 is 90 deg counter-clockwise
                 # After rotating back, its dimensions will be original_unrotated_width x original_unrotated_height
                 target_mask_size = (original_unrotated_width, original_unrotated_height)
            else: # No rotation or already wide
                 target_mask_size = (original_unrotated_width, original_unrotated_height)

            # Resize the mask to the original image dimensions
            predicted_seg_mask_original_dims = np.array(Image.fromarray(unpadded_mask.astype(np.uint8)).resize(target_mask_size, Image.NEAREST))

            # --- Connected Component Analysis ---
            # Combine blade (1) and vein (2) into a single binary mask for connected component labeling
            combined_leaf_mask_binary = ((predicted_seg_mask_original_dims == 1) | (predicted_seg_mask_original_dims == 2)).astype(np.uint8)
            labeled_mask = label(combined_leaf_mask_binary, connectivity=2) # 8-connectivity
            properties = regionprops(labeled_mask)

            current_image_components_metadata = [] 
            component_idx_in_original_image = 1 
            
            # Use original_rgb_np for cropping and overlay, which is the original image as a numpy array
            original_rgb_np = np.array(original_pil_img)

            for region in properties:
                min_row, min_col, max_row, max_col = region.bbox
                bbox_height = max_row - min_row
                bbox_width = max_col - min_col

                # Apply Minimum Bounding Box Dimension Filter
                if bbox_height < MIN_BBOX_DIMENSION or bbox_width < MIN_BBOX_DIMENSION:
                    continue # Skip this component if its bounding box is too small
                
                # Generate unique name for the component (GLOBAL uniqueness now)
                component_base_name = f"{DATASET_PREFIX}{sanitized_cultivar}_{global_component_serial_id}"
                
                # Crop Images and Masks for this component
                cropped_rgb = original_rgb_np[min_row:max_row, min_col:max_col, :]
                
                # Get the segmentation mask for only this specific component's bounding box
                cropped_seg_mask_full_classes = predicted_seg_mask_original_dims[min_row:max_row, min_col:max_col]
                
                # Create a binary mask that only includes the pixels belonging to the current region from `labeled_mask`
                component_binary_mask_in_bbox = (labeled_mask[min_row:max_row, min_col:max_col] == region.label).astype(np.uint8)
                
                # Apply this binary mask to the cropped segmentation. 
                cropped_component_seg_mask_filtered = cropped_seg_mask_full_classes * component_binary_mask_in_bbox

                # Count Pixels for Metadata
                blade_pixels = np.sum(cropped_component_seg_mask_filtered == 1)
                vein_pixels = np.sum(cropped_component_seg_mask_filtered == 2)
                
                component_binary_only_leaf = ((cropped_component_seg_mask_filtered == 1) | 
                                            (cropped_component_seg_mask_filtered == 2)).astype(bool)
                filled_component_binary = ndimage.binary_fill_holes(component_binary_only_leaf)
                filled_leaf_area = np.sum(filled_component_binary)
                
                background_pixels_internal_holes = filled_leaf_area - (blade_pixels + vein_pixels)

                total_pixels_in_bbox = cropped_component_seg_mask_filtered.size
                
                # Save Cropped Mask
                mask_save_path = os.path.join(OUTPUT_COMPONENT_MASKS_DIR, f"{component_base_name}_mask.png")
                Image.fromarray(cropped_component_seg_mask_filtered.astype(np.uint8), mode='L').save(mask_save_path)

                # Save Cropped RGB Image
                rgb_crop_save_path = os.path.join(OUTPUT_COMPONENT_RGB_CROPS_DIR, f"{component_base_name}_rgb_crop.png")
                Image.fromarray(cropped_rgb).save(rgb_crop_save_path)

                # Generate and Save Custom Overlay (retained from WOLFSKILL script)
                plt.figure(figsize=(cropped_rgb.shape[1]/100, cropped_rgb.shape[0]/100), dpi=100)
                
                overlay_image = np.zeros_like(cropped_rgb, dtype=np.uint8) 
                blade_mask = (cropped_component_seg_mask_filtered == 1)
                overlay_image[blade_mask] = cropped_rgb[blade_mask]

                vein_mask = (cropped_component_seg_mask_filtered == 2)
                if np.any(vein_mask):
                    vein_original_rgb_pixels = cropped_rgb[vein_mask]
                    vein_grayscale_intensity = color.rgb2gray(vein_original_rgb_pixels / 255.0) 
                    colored_vein_pixels_rgba = vein_cmap(vein_grayscale_intensity)
                    overlay_image[vein_mask] = (colored_vein_pixels_rgba[:, :3] * 255).astype(np.uint8)

                plt.imshow(overlay_image) 
                
                plt.axis('off')
                plt.tight_layout(pad=0)
                
                overlay_save_path = os.path.join(OUTPUT_COMPONENT_OVERLAYS_DIR, f"{component_base_name}_overlay.png")
                plt.savefig(overlay_save_path, bbox_inches='tight', pad_inches=0, facecolor='black', transparent=False)
                plt.close() 

                # Append Metadata for Current Component
                current_image_components_metadata.append({
                    "original_image_path": original_image_full_path,
                    "cultivar": current_cultivar, 
                    "component_name": component_base_name, 
                    "component_idx_in_original_image": component_idx_in_original_image, 
                    "blade_pixels": blade_pixels,
                    "vein_pixels": vein_pixels,
                    "background_pixels_internal_holes": background_pixels_internal_holes,
                    "total_bbox_pixels": total_pixels_in_bbox,
                    "bbox_min_row": min_row,
                    "bbox_min_col": min_col,
                    "bbox_max_row": max_row,
                    "bbox_max_col": max_col,
                    "mask_file": os.path.basename(mask_save_path),
                    "rgb_crop_file": os.path.basename(rgb_crop_save_path),
                    "overlay_file": os.path.basename(overlay_save_path)
                })
                
                global_component_serial_id += 1 
                component_idx_in_original_image += 1 
            
            # Append components from the current image to the overall metadata list
            # and immediately save the updated CSV
            if current_image_components_metadata:
                all_component_metadata.extend(current_image_components_metadata)
                metadata_df = pd.DataFrame(all_component_metadata)
                metadata_df.to_csv(METADATA_CSV_PATH, index=False)

        except Exception as e:
            print(f"❌ Error processing {os.path.basename(original_image_full_path)}: {e}. Skipping this image.")


    print(f"\n✅ Prediction and component extraction complete! Results saved to '{OUTPUT_PREDICTIONS_DIR}' folder.")

if __name__ == "__main__":
    main()