import torch
import torch.nn as nn
from torch.utils.data import Dataset, DataLoader, random_split
from PIL import Image
import pandas as pd
from pathlib import Path
import numpy as np
import matplotlib.pyplot as plt
import sys
import random 
import os 

# --- Configuration Parameters (must match training script) ---
IMAGE_SIZE = (256, 256)
SYNTHETIC_DATA_OUTPUT_DIR = Path("synthetic_leaf_data/")
SYNTHETIC_METADATA_FILE = SYNTHETIC_DATA_OUTPUT_DIR / "synthetic_metadata.csv"
MODEL_SAVE_PATH = Path("trained_leaf_segmentation_model.pth") # Path to your saved model

# --- Visualization Output Path ---
VISUALIZATION_OUTPUT_DIR = Path("prediction_visualizations/")

# --- Device Configuration (must match training script for loading) ---
def get_device():
    if torch.backends.mps.is_available():
        return torch.device("mps")
    elif torch.cuda.is_available():
        return torch.device("cuda")
    return torch.device("cpu")

DEVICE = get_device()
print(f"Using device: {DEVICE}")

# --- 1. Custom Dataset Class (identical to training script, with filename key update) ---
class SyntheticLeafDataset(Dataset):
    def __init__(self, metadata_file: Path, base_dir: Path, transform=None):
        self.metadata_df = pd.read_csv(metadata_file)
        self.metadata_df = self.metadata_df[self.metadata_df['is_processed_valid']].reset_index(drop=True)
        self.base_dir = base_dir
        self.transform = transform

        if self.metadata_df.empty:
            raise ValueError(f"No valid processed samples found in metadata file: {metadata_file}")
            
        print(f"Loaded {len(self.metadata_df)} valid synthetic samples for visualization.")

        # --- IMPORTANT: Check for the correct column name here ---
        # Prioritize 'image_name' (as generated by my latest script)
        # Fallback to 'synthetic_id' if that's what's in your CSV
        if 'image_name' in self.metadata_df.columns:
            self.filename_col = 'image_name'
        elif 'synthetic_id' in self.metadata_df.columns:
            self.filename_col = 'synthetic_id'
        else:
            raise ValueError(
                "Neither 'image_name' nor 'synthetic_id' column found in your metadata CSV. "
                "Please check your 'synthetic_metadata.csv' file to identify the correct column "
                "for unique image identifiers."
            )
        print(f"Using '{self.filename_col}' as the filename column from metadata.")


    def __len__(self):
        return len(self.metadata_df)

    def __getitem__(self, idx):
        row = self.metadata_df.iloc[idx]
        
        blade_ect_path = self.base_dir / row['file_blade_ect']
        blade_ect_img = Image.open(blade_ect_path).convert("L")
        
        blade_mask_path = self.base_dir / row['file_blade_mask']
        blade_mask_img = Image.open(blade_mask_path).convert("L")

        vein_mask_path = self.base_dir / row['file_vein_mask']
        vein_mask_img = Image.open(vein_mask_path).convert("L")

        blade_ect_np = np.array(blade_ect_img) / 255.0
        blade_mask_np = np.array(blade_mask_img) / 255.0
        vein_mask_np = np.array(vein_mask_img) / 255.0

        inputs_stacked = np.stack([blade_ect_np, blade_mask_np], axis=0)
        inputs_tensor = torch.from_numpy(inputs_stacked).float()

        target_tensor = torch.from_numpy(vein_mask_np).float().unsqueeze(0)

        if self.transform:
             pass 

        return inputs_tensor, target_tensor, row[self.filename_col] # Use the dynamic filename column


# --- 2. Model Architecture: U-Net (identical to training script) ---
class DoubleConv(nn.Module):
    """(convolution => [BN] => ReLU) * 2"""
    def __init__(self, in_channels, out_channels):
        super().__init__()
        self.double_conv = nn.Sequential(
            nn.Conv2d(in_channels, out_channels, kernel_size=3, padding=1),
            nn.BatchNorm2d(out_channels),
            nn.ReLU(inplace=True),
            nn.Conv2d(out_channels, out_channels, kernel_size=3, padding=1),
            nn.BatchNorm2d(out_channels),
            nn.ReLU(inplace=True)
        )

    def forward(self, x):
        return self.double_conv(x)

class Down(nn.Module):
    """Downscaling with maxpool then double conv"""
    def __init__(self, in_channels, out_channels):
        super().__init__()
        self.maxpool_conv = nn.Sequential(
            nn.MaxPool2d(2),
            DoubleConv(in_channels, out_channels)
        )

    def forward(self, x):
        return self.maxpool_conv(x)

class Up(nn.Module):
    """Upscaling then double conv"""
    def __init__(self, in_channels, out_channels, bilinear=True):
        super().__init__()
        if bilinear:
            self.up = nn.Upsample(scale_factor=2, mode='bilinear', align_corners=True)
            self.conv = DoubleConv(in_channels, out_channels) 
        else:
            self.up = nn.ConvTranspose2d(in_channels // 2, in_channels // 2, kernel_size=2, stride=2)
            self.conv = DoubleConv(in_channels, out_channels) 

    def forward(self, x1, x2):
        x1 = self.up(x1)
        diffY = x2.size()[2] - x1.size()[2]
        diffX = x2.size()[3] - x1.size()[3]
        x1 = nn.functional.pad(x1, [diffX // 2, diffX - diffX // 2,
                                     diffY // 2, diffY - diffY // 2])
        x = torch.cat([x2, x1], dim=1)
        return self.conv(x)

class OutConv(nn.Module):
    def __init__(self, in_channels, out_channels):
        super().__init__()
        self.conv = nn.Conv2d(in_channels, out_channels, kernel_size=1)

    def forward(self, x):
        return self.conv(x)

class UNet(nn.Module):
    def __init__(self, n_channels_in, n_classes_out, bilinear=True):
        super(UNet, self).__init__()
        self.n_channels_in = n_channels_in
        self.n_classes_out = n_classes_out
        self.bilinear = bilinear

        self.inc = DoubleConv(n_channels_in, 64)
        self.down1 = Down(64, 128)
        self.down2 = Down(128, 256)
        self.down3 = Down(256, 512)
        self.down4 = Down(512, 1024 // (2 if bilinear else 1)) 
        
        self.up1 = Up(1024, 512 // (2 if bilinear else 1), bilinear)
        self.up2 = Up(512, 256 // (2 if bilinear else 1), bilinear)
        self.up3 = Up(256, 128 // (2 if bilinear else 1), bilinear)
        self.up4 = Up(128, 64, bilinear)
        self.outc = OutConv(64, n_classes_out)

    def forward(self, x):
        x1 = self.inc(x)
        x2 = self.down1(x1)
        x3 = self.down2(x2)
        x4 = self.down3(x3)
        x5 = self.down4(x4)
        x = self.up1(x5, x4)
        x = self.up2(x, x3)
        x = self.up3(x, x2)
        x = self.up4(x, x1)
        logits = self.outc(x)
        return logits


# --- Function to save predictions with analysis ---
def save_predictions_with_analysis(model, dataset, output_dir: Path):
    model.eval() # Set to evaluation mode
    output_dir.mkdir(parents=True, exist_ok=True) # Create output directory if it doesn't exist

    # Define color-blind friendly and high-contrast colors (RGB 0-255)
    TP_COLOR = [30, 144, 255]    # DodgerBlue for True Positives
    FP_COLOR = [255, 0, 255]     # Magenta for False Positives
    FN_COLOR = [255, 255, 255]   # White for False Negatives
    OVERLAY_COLOR = [255, 165, 0] # Orange for vein overlay (on original ECT)

    print(f"\nGenerating and saving visualizations to: {output_dir}")

    num_samples_to_process = len(dataset)

    with torch.no_grad():
        for i in range(num_samples_to_process):
            inputs, target_mask, image_name = dataset[i] # image_name is now dynamically retrieved
            
            # Add batch dimension and move to device
            inputs = inputs.unsqueeze(0).to(DEVICE)

            predicted_logits = model(inputs)
            predicted_mask = torch.sigmoid(predicted_logits) # Convert logits to probabilities
            predicted_mask = (predicted_mask > 0.5).float() # Threshold to binary (0 or 1)

            # Move tensors back to CPU and convert to numpy for plotting
            inputs_cpu = inputs.squeeze(0).cpu() # Remove batch dim
            blade_ect_viz = inputs_cpu[0].numpy()
            blade_mask_viz = inputs_cpu[1].numpy()
            ground_truth_mask_viz = target_mask.squeeze().cpu().numpy() # Ensure (H, W)
            predicted_mask_viz = predicted_mask.squeeze().cpu().numpy() # Ensure (H, W)

            # --- Create composite visualization (TP, FP, FN) ---
            composite_mask = np.zeros((*ground_truth_mask_viz.shape, 3), dtype=np.uint8) 
            composite_mask[ (predicted_mask_viz == 1) & (ground_truth_mask_viz == 1) ] = TP_COLOR
            composite_mask[ (predicted_mask_viz == 1) & (ground_truth_mask_viz == 0) ] = FP_COLOR
            composite_mask[ (predicted_mask_viz == 0) & (ground_truth_mask_viz == 1) ] = FN_COLOR

            # --- Create Prediction Overlay on Leaf ECT ---
            # Convert blade_ect_viz to 3 channels for overlay
            blade_ect_rgb = np.stack([blade_ect_viz*255]*3, axis=-1).astype(np.uint8)
            overlay_image = blade_ect_rgb.copy()
            # Where prediction is 1, overlay with OVERLAY_COLOR
            # Use boolean indexing for overlay_image directly
            overlay_mask_indices = predicted_mask_viz == 1
            if overlay_mask_indices.any(): # Only apply if there are predicted pixels
                overlay_image[overlay_mask_indices] = (
                    overlay_image[overlay_mask_indices].astype(np.float32) * 0.5 + np.array(OVERLAY_COLOR).astype(np.float32) * 0.5
                )
                overlay_image[overlay_mask_indices] = np.clip(overlay_image[overlay_mask_indices], 0, 255).astype(np.uint8)


            # --- Plotting in a 2x3 grid ---
            fig, axes = plt.subplots(2, 3, figsize=(15, 10)) # Adjust figsize for squareish
            axes = axes.flatten() # Flatten array for easy indexing

            titles = [
                "1. Input: Leaf ECT",
                "2. Input: Blade Mask",
                "3. Ground Truth: Vein Mask",
                "4. Predicted: Vein Mask",
                "5. Analysis: TP (Blue), FP (Magenta), FN (White)",
                "6. Prediction Overlay on Leaf ECT"
            ]
            images = [
                blade_ect_viz,
                blade_mask_viz,
                ground_truth_mask_viz,
                predicted_mask_viz,
                composite_mask,
                overlay_image
            ]
            cmaps = ['gray', 'gray', 'gray', 'gray', None, None] # No cmap for RGB images

            for j, ax in enumerate(axes):
                ax.imshow(images[j], cmap=cmaps[j])
                ax.set_title(titles[j])
                ax.axis('off')

            plt.tight_layout()
            
            # Save the figure
            save_path = output_dir / f"{image_name}_prediction.png"
            plt.savefig(save_path, bbox_inches='tight', dpi=150) # Increased DPI for better quality
            plt.close(fig) # Close the figure to free up memory

            if (i + 1) % 100 == 0 or (i + 1) == num_samples_to_process:
                print(f"Processed {i+1}/{num_samples_to_process} samples.")

    print(f"\nAll {num_samples_to_process} visualizations saved to {output_dir}")


# --- Main Execution ---
if __name__ == "__main__":
    # Create dataset
    try:
        dataset = SyntheticLeafDataset(SYNTHETIC_METADATA_FILE, SYNTHETIC_DATA_OUTPUT_DIR)
    except ValueError as e:
        print(f"Error creating dataset: {e}")
        print("Please ensure the synthetic data generation script has been run successfully and the metadata file exists.")
        sys.exit(1)

    if not MODEL_SAVE_PATH.exists():
        print(f"Error: Trained model not found at {MODEL_SAVE_PATH}")
        print("Please ensure the training script (1_train_unet.py) has been run successfully.")
        sys.exit(1)

    if len(dataset) == 0:
        print("No samples available in the dataset for visualization.")
        sys.exit(1)

    # Initialize model
    inference_model = UNet(n_channels_in=2, n_classes_out=1).to(DEVICE)
    inference_model.load_state_dict(torch.load(MODEL_SAVE_PATH, map_location=DEVICE))
    inference_model.eval() # Set to evaluation mode

    print(f"Loaded model from: {MODEL_SAVE_PATH}")

    # Call the function to save all predictions
    save_predictions_with_analysis(inference_model, dataset, VISUALIZATION_OUTPUT_DIR)

    print("\n--- Visualization process complete ---")
    print(f"Check the '{VISUALIZATION_OUTPUT_DIR}' folder for all saved plots.")